import sys
import csv

#
#
#

#
print('set of [open "cg.xyz" w]')
print('')
print('# definitions:')

i=1
with open('Piezo 2 repeat 1 Mapping.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        print('set cg'+str(i)+' [atomselect top "name CA and resid ', row['Resid 1'], row['Resid 2'], row['Resid 3']+'"]')
        i+=1

print('')
print('# centres-of-mass:')

print('puts $of '+str(i-1))
print('puts $of "autogenerated by '+str(sys.argv[0])+'"')
for j in range(1,i):
    print('puts -nonewline $of "X "')
    print('puts $of [measure center $cg'+str(j)+']')

print('')
print('quit')