set of [open "cg.xyz" w]

# definitions:
set cg1 [atomselect top "name CA and resid  2236 2237 2238"]
set cg2 [atomselect top "name CA and resid  2239 2240 2241"]
set cg3 [atomselect top "name CA and resid  2242 2243 2244"]
set cg4 [atomselect top "name CA and resid  2245 2246 2247"]
set cg5 [atomselect top "name CA and resid  2248 2249 2250"]
set cg6 [atomselect top "name CA and resid  2251 2252 2253"]
set cg7 [atomselect top "name CA and resid  2254 2255 2256"]
set cg8 [atomselect top "name CA and resid  2257 2258 2259"]
set cg9 [atomselect top "name CA and resid  2260 2261 2262"]
set cg10 [atomselect top "name CA and resid  2263 2264 2265"]
set cg11 [atomselect top "name CA and resid  2266 2267 2268"]
set cg12 [atomselect top "name CA and resid  2269 2270 2271"]
set cg13 [atomselect top "name CA and resid  2272 2273 2274"]
set cg14 [atomselect top "name CA and resid  2275 2276 2277"]
set cg15 [atomselect top "name CA and resid  2278 2279 2280"]
set cg16 [atomselect top "name CA and resid  2281 2282 "]
set cg17 [atomselect top "name CA and resid  2299 2300 "]
set cg18 [atomselect top "name CA and resid  2301 2302 2303"]
set cg19 [atomselect top "name CA and resid  2304 2305 2306"]
set cg20 [atomselect top "name CA and resid  2307 2308 2309"]
set cg21 [atomselect top "name CA and resid  2310 2311 2312"]
set cg22 [atomselect top "name CA and resid  2313 2314 2315"]
set cg23 [atomselect top "name CA and resid  2316 2317 2318"]
set cg24 [atomselect top "name CA and resid  2319 2320 2321"]
set cg25 [atomselect top "name CA and resid  2322 2323 2324"]
set cg26 [atomselect top "name CA and resid  2325 2326 2327"]
set cg27 [atomselect top "name CA and resid  2328 2329 2330"]
set cg28 [atomselect top "name CA and resid  2331 2332 2333"]
set cg29 [atomselect top "name CA and resid  2334 2335 2336"]
set cg30 [atomselect top "name CA and resid  2337 2338 2339"]
set cg31 [atomselect top "name CA and resid  2340 2341 2342"]
set cg32 [atomselect top "name CA and resid  2343 2344 2345"]
set cg33 [atomselect top "name CA and resid  2346 2347 2348"]
set cg34 [atomselect top "name CA and resid  2349 2350 2351"]
set cg35 [atomselect top "name CA and resid  2352 2353 2354"]
set cg36 [atomselect top "name CA and resid  2355 2356 2357"]
set cg37 [atomselect top "name CA and resid  2358 2359 2360"]
set cg38 [atomselect top "name CA and resid  2361 2362 2363"]
set cg39 [atomselect top "name CA and resid  2364 2365 2366"]
set cg40 [atomselect top "name CA and resid  2367 2368 2369"]
set cg41 [atomselect top "name CA and resid  2370 2371 2372"]
set cg42 [atomselect top "name CA and resid  2373 2374 2375"]
set cg43 [atomselect top "name CA and resid  2376 2377 2378"]
set cg44 [atomselect top "name CA and resid  2379 2380 2381"]
set cg45 [atomselect top "name CA and resid  2382 2383 2384"]
set cg46 [atomselect top "name CA and resid  2385 2386 2387"]
set cg47 [atomselect top "name CA and resid  2388 2389 2390"]

# centres-of-mass:
puts $of 47
puts $of "autogenerated by parse_csv.py"
puts -nonewline $of "X "
puts $of [measure center $cg1]
puts -nonewline $of "X "
puts $of [measure center $cg2]
puts -nonewline $of "X "
puts $of [measure center $cg3]
puts -nonewline $of "X "
puts $of [measure center $cg4]
puts -nonewline $of "X "
puts $of [measure center $cg5]
puts -nonewline $of "X "
puts $of [measure center $cg6]
puts -nonewline $of "X "
puts $of [measure center $cg7]
puts -nonewline $of "X "
puts $of [measure center $cg8]
puts -nonewline $of "X "
puts $of [measure center $cg9]
puts -nonewline $of "X "
puts $of [measure center $cg10]
puts -nonewline $of "X "
puts $of [measure center $cg11]
puts -nonewline $of "X "
puts $of [measure center $cg12]
puts -nonewline $of "X "
puts $of [measure center $cg13]
puts -nonewline $of "X "
puts $of [measure center $cg14]
puts -nonewline $of "X "
puts $of [measure center $cg15]
puts -nonewline $of "X "
puts $of [measure center $cg16]
puts -nonewline $of "X "
puts $of [measure center $cg17]
puts -nonewline $of "X "
puts $of [measure center $cg18]
puts -nonewline $of "X "
puts $of [measure center $cg19]
puts -nonewline $of "X "
puts $of [measure center $cg20]
puts -nonewline $of "X "
puts $of [measure center $cg21]
puts -nonewline $of "X "
puts $of [measure center $cg22]
puts -nonewline $of "X "
puts $of [measure center $cg23]
puts -nonewline $of "X "
puts $of [measure center $cg24]
puts -nonewline $of "X "
puts $of [measure center $cg25]
puts -nonewline $of "X "
puts $of [measure center $cg26]
puts -nonewline $of "X "
puts $of [measure center $cg27]
puts -nonewline $of "X "
puts $of [measure center $cg28]
puts -nonewline $of "X "
puts $of [measure center $cg29]
puts -nonewline $of "X "
puts $of [measure center $cg30]
puts -nonewline $of "X "
puts $of [measure center $cg31]
puts -nonewline $of "X "
puts $of [measure center $cg32]
puts -nonewline $of "X "
puts $of [measure center $cg33]
puts -nonewline $of "X "
puts $of [measure center $cg34]
puts -nonewline $of "X "
puts $of [measure center $cg35]
puts -nonewline $of "X "
puts $of [measure center $cg36]
puts -nonewline $of "X "
puts $of [measure center $cg37]
puts -nonewline $of "X "
puts $of [measure center $cg38]
puts -nonewline $of "X "
puts $of [measure center $cg39]
puts -nonewline $of "X "
puts $of [measure center $cg40]
puts -nonewline $of "X "
puts $of [measure center $cg41]
puts -nonewline $of "X "
puts $of [measure center $cg42]
puts -nonewline $of "X "
puts $of [measure center $cg43]
puts -nonewline $of "X "
puts $of [measure center $cg44]
puts -nonewline $of "X "
puts $of [measure center $cg45]
puts -nonewline $of "X "
puts $of [measure center $cg46]
puts -nonewline $of "X "
puts $of [measure center $cg47]

quit
